### PR TITLE
Fix small bugs

### PR DESCRIPTION
**Pull request by mth-1012**
# General info

**Issue number**: #83 #86 #87 

**What changed**:

Doctor:

image

Health Official

image

Immigration Official

image

Appointment

image

# Testing

Manual and visual test.

# Additional notes

**Note to reviewers**: Nothing

**To do before merging**:
- [ ] Edit Changelog(if necessary)

### CODE REVIEW

**Comment by mth-1012** [comment]
The flag badge is still mis-behaving but will be fixed in PR #90

**Comment by mth-1012** [comment]
Added a checkbox for flagged patients. Not visible on administrator page

image

**Comment by BunnyPrince** [comment]
I see that this patient is flagged but we don't see it when we filter it next to their name  like you said 

for the Appointment is will be better if we have a button or a text link at the top to go directly to the bottom in the place of us scrolling down 

but everything else looks good

**Comment by AC159** [comment]
When I press the checkbox to see the flagged patients, I also see patient that are not flagged:
image

**Comment by AC159** [comment]
Also, concerning the doctor booking appointments. The user should not be able to submit an appointment form without choosing the date, time and filling the required fields. These should be validated before submitting any form.

**Comment by mth-1012** [comment]
Yeah re. the check box and search box results not showing correct results. It's actually showing **the** correct results, only the "flagged" badge is mis-behaving. That will be fixed in PR #90. I tested it there.

Thanks for your concern though! I'll look into the other things you guys mentioned.

**Comment by mth-1012** [comment]
@BunnyPrince I moved the appointment to the top
@AC159 Alert for empty fields added

Scheduled appointments are now updated instantly after an appointment is submitted.

**Review by DrakeHunterK7 — COMMENTED** [review]
image

When the doctor goes to the appointment tab, a user by default is selected. But if you don't change that user and go on to fill everything else and then submit, the appointment is submitted with all fields except for the name of the patient.

**Review by DrakeHunterK7 — APPROVED** [review]
Looks like with new changes everything looks good! There are some existing issues but looks like they were fixed in #90 so for all intents and purposes this PR is good to go.

**Review by AC159 — APPROVED** [review]

**Pull request merged**
