### PR TITLE
Update profile frontend

### PR DESCRIPTION
**Pull request by AC159**
# General info

**Task description**: 

 - current user information is accessible throughout the application
 - more error handling during login
 - added redirect when a user wants to access a page but is not authenticated

# Testing

**Test coverage**:
The code was tested manually

# Additional notes

**Note to reviewers**:
Test the code before merging

**To do before merging**:
- Create an account on the sign up page
- Click on the user avatar to be redirected to the user-profile page and see if the your information is displayed there
- Try to navigate to a route that requires authentication (make sure you're not logged in) and you should be redirected to that same page after login

### CODE REVIEW

**Comment by mth-1012** [comment]
- I can see the content of /user-profile ONLY after I sign-up.
- When I click on the avatar after logging in to an existing account, nothing is shown in /user-profile, blank like image
- When I try to access a route that requires logging in, it does require me to log in (which is good), and I'm redirected to that route. However, the page (sometimes) shows up for like half a second and then (always) goes all blank like image

image

**Comment by mth-1012** [comment]
apparently the problem is currentUser is blank after logging in but is okay after signing up

**Comment by AC159** [comment]
> found the reason: no axios in Login.js
Actually, axios is imported in login.js

**Comment by mth-1012** [comment]
yeah my bad... axios is not related... but the problem about the blank pages is there

**Comment by AC159** [comment]
> yeah my bad... axios is not related... but the problem about the blank pages is there

Can you show a screenshot of the console logs in the browser?

**Comment by mth-1012** [comment]
image

**Comment by AC159** [comment]
> image

It seems that the database did not send any data since the field is empty in the db response. Can you confirm?
Otherwise, is the currentUser object populated?

**Comment by mth-1012** [comment]
image

inside "Current User". there's just a [[Prototype]] Object 

image

**Pull request merged**
