### PR TITLE
#5 implemented basic login with firebase and corresponding frontend r…

### PR DESCRIPTION
**Pull request by AC159**
### General Info
**Issue Number: 5**
**Task Description:**
- Implement Firebase Sign Up/Login functionality for the Front-end
- Handling different routes in the Front-end
- Check for authentication status before allowing user on a certain route
- Check for email & password validity before registering an account

### Testing
**No test coverage**

### Additional notes
**Note to reviewers:** This PR implements the logical skeleton of the Front-end for authentication with Firebase and route handling and it is NOT about creating all kinds of components such as navigation bar and user dashboards with their respective styles.
**To do before merging:** 

1. Ensure that you can create an account (and that you are redirected without error in the console) & that your authentication has been registered in the Firebase console (everyone has access to it).
2. Verify that you can login properly
3. Verify that you are redirected to the login page whenever you try to go directly to the patient dashboard ('/patient-dashboard')

### CODE REVIEW

**Comment by BunnyPrince** [comment]
- The signing up is working 
- The redirection to patient dashboard is working
- logging in with the same credential is working 

Shouldn't we redirected to a page that's more a normal person dashboard when we sigh up because if the admin didn't assign a role to the user when they sign up then  it doesn't make sense that their are redirected to patient dashboard?

It's better if we redirected to a page where we can select a user (patient, doctor, health officer or immigration officer). After the request is approved by the admin then the user can log into his/her respective dashboard.

**Comment by mth-1012** [comment]
only talking about the feature
- yes signing up is working, but the password must include letter AND number, which wasn't mentioned (not sure why tho, can be fixed easily)
- yes logging in is working too!

not sure about the redirecting yet since we haven't agreed on that yet

**Comment by AC159** [comment]
> Shouldn't we redirected to a page that's more a normal person dashboard when we sigh up because if the admin didn't assign a role to the user when they sign up then it doesn't make sense that their are redirected to patient dashboard?
> 
> It's better if we redirected to a page where we can select a user (patient, doctor, health officer or immigration officer). After the request is approved by the admin then the user can log into his/her respective dashboard.

This PR is not about redirecting to the correct/incorrect page. It's about providing front-end authentication and a skeleton for the app. We can redirect to other pages once a user signs up.

**Review by DrakeHunterK7 — APPROVED** [review]
Everything works well! 

1) I can create an account and Firebase registers my authentication.
2) I can log in using the info I entered on the sign up page.
3) I am unable to go to the patient dashboard directly. If I manually copy and paste the patient dashboard url, it redirects me to the login page. 

All in all, great work!

Now that it everyone else has verified and reviewed this pull request, should I go ahead and merge it with main? Everything looks good to me.

**Review by BunnyPrince — APPROVED** [review]
Everything looks good

**Pull request merged**
